/*
 * License: 3-clause BSD. See LICENSE file in root directory.
 * Copyright(c) 2015-2016 Intel Corporation. All Rights Reserved.
 * */

#ifndef CLOCALIZATION_H_
#define CLOCALIZATION_H_
#include "KeyFrameSimple.h"
#include <string>
#include <vector>

class cLocalization
{
public:
	cLocalization(std::string g2oPath, std::string xmlPath);
	~cLocalization();
	// get absolute pose of camera
	Eigen::Matrix4f GetAbsoluteCamPose(std::string candidateName, const Eigen::Matrix4f &relativePose, float camScale=1.0f);
	// get the absolute pose of keyframe
	Eigen::Matrix4f GetKeyframePose(std::string candidateName, float camScale = 1.0f);
protected:
	// load the xml files, generated by slam program
	void LoadKeyFrameList(std::string xmlPath);
private:
	std::vector<KeyFrameSimple> keyframeSimpleList;
	std::string g2oPath;
};

#endif
