set(PREBUILT_LIBS "")

add_definitions(-DEIGEN_USE_NEW_STDVECTOR;-DEIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET;-DFLANN_STATIC)
add_definitions(-DDISABLE_OPENNI -DDISABLE_OPENNI2 -DDISABLE_PCAP -DDISABLE_PNG)

include_directories(${CMAKE_SOURCE_DIR}/3rdparty/opencv/include)
include_directories(${CMAKE_SOURCE_DIR}/3rdparty/Eigen/include)
include_directories(${CMAKE_SOURCE_DIR}/3rdparty/Boost/include)
include_directories(${CMAKE_SOURCE_DIR}/3rdparty/VTK_5.10.1/include)
include_directories(${CMAKE_SOURCE_DIR}/3rdparty/PCL_1.7.2/include)
include_directories(${CMAKE_SOURCE_DIR}/3rdparty/g2o/include)
include_directories(${CMAKE_SOURCE_DIR}/3rdparty/librealsense/include)

if(X64_VERSION_BUILD)
    link_directories(${CMAKE_SOURCE_DIR}/3rdparty/Boost/lib/x64)
    link_directories(${CMAKE_SOURCE_DIR}/3rdparty/VTK_5.10.1/lib/x64)
    link_directories(${CMAKE_SOURCE_DIR}/3rdparty/g2o/lib/x64)
    link_directories(${CMAKE_SOURCE_DIR}/3rdparty/librealsense/lib/x64)
    link_directories(${CMAKE_SOURCE_DIR}/3rdparty/PCL_1.7.2/lib/x64)
    link_directories(${CMAKE_SOURCE_DIR}/3rdparty/opencv/lib/x64)

    file(GLOB OPENCV_LIBS_OPT "${CMAKE_SOURCE_DIR}/3rdparty/opencv/lib/x64/*310.lib")
    file(GLOB OPENCV_LIBS_DBG "${CMAKE_SOURCE_DIR}/3rdparty/opencv/lib/x64/*310d.lib")
    file(GLOB BOOST_LIBS_OPT "${CMAKE_SOURCE_DIR}/3rdparty/Boost/lib/x64/*-mt-1_60.lib")
    file(GLOB BOOST_LIBS_DBG "${CMAKE_SOURCE_DIR}/3rdparty/Boost/lib/x64/*-mt-gd-1_60.lib")
    set(G2O_LIBS_OPT "${CMAKE_SOURCE_DIR}/3rdparty/g2o/lib/x64/g2o_core.lib")
    list(APPEND G2O_LIBS_OPT "${CMAKE_SOURCE_DIR}/3rdparty/g2o/lib/x64/g2o_types_slam3d.lib")
    set(G2O_LIBS_DBG "${CMAKE_SOURCE_DIR}/3rdparty/g2o/lib/x64/g2o_core_d.lib")
    list(APPEND G2O_LIBS_DBG "${CMAKE_SOURCE_DIR}/3rdparty/g2o/lib/x64/g2o_types_slam3d_d.lib")
    set(LIBREALSENSE_LIBS_OPT "${CMAKE_SOURCE_DIR}/3rdparty/librealsense/lib/x64/realsense.lib")
    set(LIBREALSENSE_LIBS_DBG "${CMAKE_SOURCE_DIR}/3rdparty/librealsense/lib/x64/realsense-d.lib")
    file(GLOB VTK_LIBS_OPT "${CMAKE_SOURCE_DIR}/3rdparty/VTK_5.10.1/lib/x64/Release/*.lib")
    file(GLOB VTK_LIBS_DBG "${CMAKE_SOURCE_DIR}/3rdparty/VTK_5.10.1/lib/x64/Debug/*.lib")
    file(GLOB PCL_LIBS_OPT "${CMAKE_SOURCE_DIR}/3rdparty/PCL_1.7.2/lib/x64/*_release.lib")
    file(GLOB PCL_LIBS_DBG "${CMAKE_SOURCE_DIR}/3rdparty/PCL_1.7.2/lib/x64/*_debug.lib")
else()
    link_directories(${CMAKE_SOURCE_DIR}/3rdparty/Boost/lib/Win32)
    link_directories(${CMAKE_SOURCE_DIR}/3rdparty/VTK_5.10.1/lib/Win32)
    link_directories(${CMAKE_SOURCE_DIR}/3rdparty/g2o/lib/Win32)
    link_directories(${CMAKE_SOURCE_DIR}/3rdparty/librealsense/lib/Win32)
    link_directories(${CMAKE_SOURCE_DIR}/3rdparty/PCL_1.7.2/lib/Win32)
    link_directories(${CMAKE_SOURCE_DIR}/3rdparty/opencv/lib/Win32)

    file(GLOB OPENCV_LIBS_OPT "${CMAKE_SOURCE_DIR}/3rdparty/opencv/lib/Win32/*310.lib")
    file(GLOB OPENCV_LIBS_DBG "${CMAKE_SOURCE_DIR}/3rdparty/opencv/lib/Win32/*310d.lib")
    file(GLOB BOOST_LIBS_OPT "${CMAKE_SOURCE_DIR}/3rdparty/Boost/lib/Win32/*-mt-1_60.lib")
    file(GLOB BOOST_LIBS_DBG "${CMAKE_SOURCE_DIR}/3rdparty/Boost/lib/Win32/*-mt-gd-1_60.lib")
    set(G2O_LIBS_OPT "${CMAKE_SOURCE_DIR}/3rdparty/g2o/lib/Win32/g2o_core.lib")
    list(APPEND G2O_LIBS_OPT "${CMAKE_SOURCE_DIR}/3rdparty/g2o/lib/Win32/g2o_types_slam3d.lib")
    set(G2O_LIBS_DBG "${CMAKE_SOURCE_DIR}/3rdparty/g2o/lib/Win32/g2o_core_d.lib")
    list(APPEND G2O_LIBS_DBG "${CMAKE_SOURCE_DIR}/3rdparty/g2o/lib/Win32/g2o_types_slam3d_d.lib")
    set(LIBREALSENSE_LIBS_OPT "${CMAKE_SOURCE_DIR}/3rdparty/librealsense/lib/Win32/realsense.lib")
    set(LIBREALSENSE_LIBS_DBG "${CMAKE_SOURCE_DIR}/3rdparty/librealsense/lib/Win32/realsense-d.lib")
    file(GLOB VTK_LIBS_OPT "${CMAKE_SOURCE_DIR}/3rdparty/VTK_5.10.1/lib/Win32/Release/*.lib")
    file(GLOB VTK_LIBS_DBG "${CMAKE_SOURCE_DIR}/3rdparty/VTK_5.10.1/lib/Win32/Debug/*.lib")
    file(GLOB PCL_LIBS_OPT "${CMAKE_SOURCE_DIR}/3rdparty/PCL_1.7.2/lib/Win32/*_release.lib")
    file(GLOB PCL_LIBS_DBG "${CMAKE_SOURCE_DIR}/3rdparty/PCL_1.7.2/lib/Win32/*_debug.lib")
endif()

list(APPEND PREBUILT_LIBS "vfw32.lib")
list(APPEND PREBUILT_LIBS "ws2_32.lib")
list(APPEND PREBUILT_LIBS "opengl32.lib")
list(APPEND PREBUILT_LIBS "comctl32.lib")
list(APPEND PREBUILT_LIBS "wsock32.lib")

if(CMAKE_BUILD_TYPE MATCHES "Debug")
    list(APPEND PREBUILT_LIBS ${OPENCV_LIBS_DBG})
    list(APPEND PREBUILT_LIBS ${BOOST_LIBS_DBG})
    list(APPEND PREBUILT_LIBS ${G2O_LIBS_DBG})
    list(APPEND PREBUILT_LIBS ${LIBREALSENSE_LIBS_DBG})
    list(APPEND PREBUILT_LIBS ${VTK_LIBS_DBG})
    list(APPEND PREBUILT_LIBS ${PCL_LIBS_DBG})
else()
    list(APPEND PREBUILT_LIBS ${OPENCV_LIBS_OPT})
    list(APPEND PREBUILT_LIBS ${BOOST_LIBS_OPT})
    list(APPEND PREBUILT_LIBS ${G2O_LIBS_OPT})
    list(APPEND PREBUILT_LIBS ${LIBREALSENSE_LIBS_OPT})
    list(APPEND PREBUILT_LIBS ${VTK_LIBS_OPT})
    list(APPEND PREBUILT_LIBS ${PCL_LIBS_OPT})
endif()
